name: Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - components/**/Dockerfile

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        component:
          - u-boot
          - kernel
          # - os
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/${{ github.repository }}/build-${{ matrix.component }}:latest
          context: components/${{ matrix.component }}
          sbom: true
          provenance: true
          cache-from: type=gha
          cache-to: type=gha
