name: CI

on:
  push:
    branches:
      - main

jobs:
  build-u-boot:
    runs-on: ubuntu-latest
    env:
      ARCH: arm
      CROSS_COMPILE: aarch64-linux-gnu-
      ROCKCHIP_TPL: ${{ github.workspace }}/rkbin/bin/rk35/rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.18.bin
      BL31: ${{ github.workspace }}/rkbin/bin/rk35/rk3588_bl31_v1.47.elf
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          repository: u-boot/u-boot
          path: u-boot
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          repository: rockchip-linux/rkbin
          path: rkbin
      - uses: actions/checkout@v4
        with:
          path: _custom

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            gcc \
            gcc-aarch64-linux-gnu \
            bc \
            bison \
            coccinelle \
            device-tree-compiler \
            dfu-util \
            efitools \
            flex \
            gdisk \
            graphviz \
            imagemagick \
            liblz4-tool \
            libgnutls28-dev \
            libguestfs-tools \
            libncurses-dev \
            libpython3-dev \
            libsdl2-dev \
            libssl-dev \
            lz4 \
            lzma \
            lzma-alone \
            openssl \
            pkg-config \
            python3 \
            python3-asteval \
            python3-coverage \
            python3-filelock \
            python3-pkg-resources \
            python3-pycryptodome \
            python3-pyelftools \
            python3-pytest \
            python3-pytest-xdist \
            python3-sphinxcontrib.apidoc \
            python3-sphinx-rtd-theme \
            python3-subunit \
            python3-testtools \
            python3-virtualenv \
            swig \
            uuid-dev

      - name: Make config
        working-directory: u-boot
        run: |
          make turing-rk1-rk3588_defconfig

      - name: Make u-boot
        working-directory: u-boot
        run: |
          make -j$(nproc)

      - name: Make boot config
        run: |
          ./u-boot/tools/mkimage -T script -d ./_custom/cmdline.txt boot.scr

      - name: Prepare artifacts
        run: |
          cp ./u-boot/idbloader.img .
          cp ./u-boot/u-boot.itb .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: u-boot
          path: |
            idbloader.img
            u-boot.itb
            boot.scr

  build-kernel:
    runs-on: ubuntu-latest
    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-
    steps:
      - uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: v6.12

      - uses: actions/checkout@v4
        with:
          path: _custom

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            gcc \
            gcc-aarch64-linux-gnu \
            bison \
            flex \
            git \
            bc \
            linux-source \
            libncurses-dev

      - name: Install config
        run: |
          cp _custom/.config .config

      - name: Make kernel
        run: |
          make -j$(nproc)
          make -j$(nproc) dtbs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/dts/rockchip/rk3588-turing-rk1.dtb
